import type { DesignSystemNavGroup } from './DesignSystemShell';

export const COMPONENT_IDS = [
  'typography',
  'links',
  'form-elements',
  'buttons',
  'icon-buttons',
  'tab-buttons',
  'quick-filters',
  'multistate-buttons',
  'text-input',
  'textbox',
  'text-area',
  'searchbox',
  'dropzone',
  'date-input',
  'currency-input',
  'dropdown',
  'multi-select-dropdown',
  'checkbox',
  'radio',
  'toggle',
  'card',
  'toggle-card',
  'table',
  'avatar',
  'status-indicator',
  'chip',
  'filter',
  'indicators',
  'document-glyph',
  'file-item',
  'country-flag',
  'tooltip',
  'tool-next-steps-card',
  'cp-workspace-shell',
  'page-header',
  'side-nav',
  'breadcrumb',
  'separator',
  'inline-banner',
  'alert',
  'toast',
] as const;

export type ComponentId = typeof COMPONENT_IDS[number];

export interface ComponentDoc {
  id: ComponentId;
  label: string;
  title: string;
  group: string;
  description: string;
  imports: string[];
  sourceFiles: string[];
  whenToUse: string[];
  guidelines: string[];
  examples: string[];
  tokens: string[];
}

export const INPUT_COMPONENT_IDS = [
  'text-input',
  'textbox',
  'text-area',
  'searchbox',
  'dropzone',
  'date-input',
  'currency-input',
  'dropdown',
  'multi-select-dropdown',
  'checkbox',
  'radio',
  'toggle',
] as const;

export type InputComponentId = typeof INPUT_COMPONENT_IDS[number];

export function isInputComponentDoc(id: string): id is InputComponentId {
  return INPUT_COMPONENT_IDS.includes(id as InputComponentId);
}

const docsByGroup: Array<{ group: string; items: Omit<ComponentDoc, 'group'>[] }> = [
  {
    group: 'Foundations',
    items: [
      {
        id: 'typography',
        label: 'Typography',
        title: 'Typography',
        description: 'Heading, body, and small text styles used across the system.',
        imports: ['Headings', 'Text'],
        sourceFiles: [
          'packages/orbit/src/primitives/Headings.tsx',
          'packages/orbit/src/primitives/Text.tsx',
        ],
        whenToUse: ['Use for all product copy so type scale, weight, and colour stay consistent.'],
        guidelines: ['Use heading levels to communicate hierarchy, not just visual size.', 'Prefer semantic text variants before applying one-off colours.'],
        examples: ['Heading 1-5', 'Primary, secondary, bold, error, information, warning, and disabled body text', 'Small text variants'],
        tokens: ['--orbit-text-*', '--orbit-font-weight-*', '--orbit-leading-*', '--orbit-color-text-*'],
      },
      {
        id: 'links',
        label: 'Links',
        title: 'Links',
        description: 'Inline link styles for primary, secondary, and heading contexts.',
        imports: ['LinkText'],
        sourceFiles: ['packages/orbit/src/actions/LinkText.tsx'],
        whenToUse: ['Use for inline navigation or actions that are visually secondary to buttons.'],
        guidelines: ['Keep link labels specific and action-oriented.', 'Use button components for primary workflow actions.'],
        examples: ['Primary link', 'Secondary link', 'Heading link'],
        tokens: ['--orbit-color-link-disabled', '--orbit-text-link-*'],
      },
      {
        id: 'form-elements',
        label: 'Form Elements',
        title: 'Form Elements',
        description: 'Shared form primitives: required indicators and carat separators.',
        imports: ['Carat', 'Required'],
        sourceFiles: [
          'packages/orbit/src/primitives/Carat.tsx',
          'packages/orbit/src/primitives/Required.tsx',
        ],
        whenToUse: ['Use for small form affordances that need to align with the wider input system.'],
        guidelines: ['Pair Required with visible field labels.', 'Use Carat only as a compact separator in labelled inline content.'],
        examples: ['Inline text separator', 'Required field marker'],
        tokens: ['--orbit-required-width', '--orbit-color-text-error'],
      },
    ],
  },
  {
    group: 'Actions',
    items: [
      {
        id: 'buttons',
        label: 'Buttons',
        title: 'Buttons',
        description: 'Primary actions, secondary options, and destructive operations.',
        imports: ['Button'],
        sourceFiles: ['packages/orbit/src/actions/Button.tsx'],
        whenToUse: ['Use for explicit commands that trigger an action or workflow step.'],
        guidelines: ['Use one primary button per decision area.', 'Reserve destructive styling for irreversible or risky actions.', 'Use icon variants when the icon adds recognition, not decoration.'],
        examples: ['Primary, secondary, tertiary, positive, and destructive variants', 'Medium and small sizes', 'Default, hover, and disabled states', 'Left and right icon buttons'],
        tokens: ['--orbit-color-btn-*', '--orbit-btn-height-*', '--orbit-btn-icon-size', '--orbit-text-button-*'],
      },
      {
        id: 'icon-buttons',
        label: 'Icon Buttons',
        title: 'Icon Buttons',
        description: 'Compact icon-only action buttons in multiple sizes and variants.',
        imports: ['IconButton', 'FaIcon'],
        sourceFiles: [
          'packages/orbit/src/actions/IconButton.tsx',
          'packages/orbit/src/primitives/FaIcon.tsx',
        ],
        whenToUse: ['Use for repeated toolbar actions, compact controls, or visually obvious commands.'],
        guidelines: ['Always provide an accessible aria label.', 'Prefer familiar icons for common actions.'],
        examples: ['Primary, secondary, tertiary, positive, and destructive variants', 'Small, medium, and large sizes', 'Default, hover, and disabled states'],
        tokens: ['--orbit-icon-btn-*', '--orbit-color-btn-*'],
      },
      {
        id: 'tab-buttons',
        label: 'Tab Buttons',
        title: 'Tab Buttons',
        description: 'Underline navigation tabs for page headers and content sections.',
        imports: ['TabButton'],
        sourceFiles: ['packages/orbit/src/navigation/TabButton.tsx'],
        whenToUse: ['Use to switch between sibling content views within the same task context.'],
        guidelines: ['Keep labels short enough to scan.', 'Avoid using tabs for unrelated destinations.'],
        examples: ['Interactive tab row', 'Rest, hover, active, and disabled states'],
        tokens: ['--orbit-tab-height', '--orbit-tab-inner-height', '--orbit-tab-underline-height'],
      },
      {
        id: 'quick-filters',
        label: 'Quick Filters',
        title: 'Quick Filters',
        description: 'Toggle-style filter chips for narrowing data views.',
        imports: ['QuickFilterGroup', 'QuickFilterItem'],
        sourceFiles: ['packages/orbit/src/navigation/QuickFilter.tsx'],
        whenToUse: ['Use for fast, visible filtering where users may toggle several options.'],
        guidelines: ['Use clear category labels.', 'Keep filter rows close to the data they affect.'],
        examples: ['Default group', 'Interactive toggles', 'Default and selected states'],
        tokens: ['--orbit-quickfilter-height', '--orbit-quickfilter-radius'],
      },
      {
        id: 'multistate-buttons',
        label: 'Grouped Buttons',
        title: 'Grouped Buttons',
        description: 'Live-matched segmented button groups for switching between related views.',
        imports: ['MultiStateGroup', 'MultiStateButton'],
        sourceFiles: ['packages/orbit/src/actions/MultiStateButton.tsx'],
        whenToUse: ['Use when a small set of mutually exclusive states controls the same view.'],
        guidelines: ['Keep groups to a manageable number of options.', 'Use counts only when they help comparison.'],
        examples: ['Mine/team switcher', 'Selected, inactive, and disabled states', 'Longer groups', 'Buttons with counts'],
        tokens: ['--orbit-multistate-*'],
      },
    ],
  },
  {
    group: 'Inputs',
    items: [
      {
        id: 'text-input',
        label: 'Text Input',
        title: 'Text Input',
        description: 'Single-line text input with default, filled, error, and disabled states.',
        imports: ['Input'],
        sourceFiles: ['packages/orbit/src/inputs/Input.tsx'],
        whenToUse: ['Use for compact free-text entry where a separate label is already present.'],
        guidelines: ['Provide an aria label when no visible label is present.', 'Use invalid state with clear nearby validation text.'],
        examples: ['Default, filled, error, and disabled states'],
        tokens: ['--orbit-color-border-*', '--orbit-color-bg-*', '--orbit-text-body-*'],
      },
      {
        id: 'textbox',
        label: 'Textbox',
        title: 'Textbox',
        description: 'Labelled text input with helper text, validation, and multiple states.',
        imports: ['Textbox'],
        sourceFiles: ['packages/orbit/src/inputs/Textbox.tsx'],
        whenToUse: ['Use for standard labelled text fields in forms.'],
        guidelines: ['Keep helper messages concise.', 'Use locked and disabled states for different meanings: unavailable versus read-only.'],
        examples: ['Empty, filled, disabled, locked, invalid, and required fields'],
        tokens: ['--orbit-color-border-*', '--orbit-color-text-*'],
      },
      {
        id: 'text-area',
        label: 'Text Area',
        title: 'Text Area',
        description: 'Multi-line text input with character count and validation.',
        imports: ['TextArea'],
        sourceFiles: ['packages/orbit/src/inputs/TextArea.tsx'],
        whenToUse: ['Use for longer comments, notes, descriptions, and instructions.'],
        guidelines: ['Set max length when there is a storage or workflow limit.', 'Avoid using for short single-value fields.'],
        examples: ['Default, filled, disabled, and invalid text areas'],
        tokens: ['--orbit-textarea-min-height', '--orbit-color-border-*'],
      },
      {
        id: 'searchbox',
        label: 'Searchbox',
        title: 'Searchbox',
        description: 'Search-specific input with icon and clearable state.',
        imports: ['Searchbox'],
        sourceFiles: ['packages/orbit/src/inputs/Searchbox.tsx'],
        whenToUse: ['Use when input changes filter or search a collection.'],
        guidelines: ['Use placeholder text to hint the searchable domain.', 'Keep search placement predictable near lists or tables.'],
        examples: ['Default, filled, disabled, and error search boxes'],
        tokens: ['--orbit-color-border-*', '--orbit-color-text-*'],
      },
      {
        id: 'dropzone',
        label: 'Dropzone',
        title: 'Dropzone',
        description: 'File upload drop area with click and drag/drop support.',
        imports: ['Dropzone'],
        sourceFiles: ['packages/orbit/src/inputs/Dropzone.tsx'],
        whenToUse: ['Use for explicit file upload moments in forms or import flows.'],
        guidelines: ['State accepted file types and size limits.', 'Show validation or disabled messaging near the drop area.'],
        examples: ['Enabled PDF uploader', 'Disabled/error uploader'],
        tokens: ['--orbit-dropzone-min-height', '--orbit-color-border-*'],
      },
      {
        id: 'date-input',
        label: 'Date Input',
        title: 'Date Input',
        description: 'Date picker input with multiple interaction states.',
        imports: ['DateInput'],
        sourceFiles: ['packages/orbit/src/inputs/DateInput.tsx'],
        whenToUse: ['Use for date values where formatting consistency matters.'],
        guidelines: ['Use disabled state for unavailable dates or locked records.', 'Use invalid state for malformed or disallowed dates.'],
        examples: ['Default, hover, focused, filled, disabled, and error states'],
        tokens: ['--orbit-color-border-*', '--orbit-color-text-*'],
      },
      {
        id: 'currency-input',
        label: 'Currency Input',
        title: 'Currency Input',
        description: 'Numeric input formatted for currency values with locale support.',
        imports: ['CurrencyInput'],
        sourceFiles: ['packages/orbit/src/inputs/CurrencyInput.tsx'],
        whenToUse: ['Use for monetary values where currency context is required.'],
        guidelines: ['Set the correct currency code.', 'Avoid mixing free-text units into the value field.'],
        examples: ['Empty, filled, disabled, and invalid GBP fields'],
        tokens: ['--orbit-color-border-*', '--orbit-color-text-*'],
      },
      {
        id: 'dropdown',
        label: 'Dropdown',
        title: 'Dropdown',
        description: 'Select input with searchable options and validation.',
        imports: ['Dropdown'],
        sourceFiles: ['packages/orbit/src/inputs/Dropdown.tsx'],
        whenToUse: ['Use when users must select one value from a finite option set.'],
        guidelines: ['Keep option labels readable and unique.', 'Use required state when selection is mandatory.'],
        examples: ['Required empty dropdown', 'Filled dropdown', 'Disabled dropdown', 'Invalid dropdown'],
        tokens: ['--orbit-dropdown-trigger-height', '--orbit-dropdown-option-height', '--orbit-dropdown-chevron-size'],
      },
      {
        id: 'multi-select-dropdown',
        label: 'Multi-select Dropdown',
        title: 'Multi-select Dropdown',
        description: 'Multi-value select input with removable selected-value chips.',
        imports: ['MultiSelectDropdown'],
        sourceFiles: ['packages/orbit/src/inputs/MultiSelectDropdown.tsx'],
        whenToUse: ['Use when users can choose multiple values from a defined set.'],
        guidelines: ['Avoid for very large option sets unless search is available.', 'Make selected values easy to remove.'],
        examples: ['Required multi-value selector with selected chip'],
        tokens: ['--orbit-dropdown-*', '--orbit-chip-*'],
      },
      {
        id: 'checkbox',
        label: 'Checkbox',
        title: 'Checkbox',
        description: 'Binary selection control with label alignment options.',
        imports: ['Checkbox'],
        sourceFiles: ['packages/orbit/src/inputs/Checkbox.tsx'],
        whenToUse: ['Use for independent yes/no choices or multi-select lists.'],
        guidelines: ['Use checkboxes when choices are not mutually exclusive.', 'Keep labels clear enough to understand in isolation.'],
        examples: ['Interactive, checked, unchecked, disabled', 'Left and right alignment'],
        tokens: ['--orbit-color-checkbox-*'],
      },
      {
        id: 'radio',
        label: 'Radio',
        title: 'Radio',
        description: 'Single-choice selection control with grouped keyboard navigation.',
        imports: ['RadioGroup', 'Radio'],
        sourceFiles: ['packages/orbit/src/inputs/Radio.tsx'],
        whenToUse: ['Use when only one option can be selected from a small set.'],
        guidelines: ['Use a group label that describes the decision.', 'Prefer dropdowns when option lists are long.'],
        examples: ['Radio group with enabled and disabled options'],
        tokens: ['--orbit-color-border-*', '--orbit-color-bg-*'],
      },
      {
        id: 'toggle',
        label: 'Toggle',
        title: 'Toggle',
        description: 'On/off switch for binary settings.',
        imports: ['Toggle'],
        sourceFiles: ['packages/orbit/src/inputs/Toggle.tsx'],
        whenToUse: ['Use for settings that take effect immediately or represent an on/off state.'],
        guidelines: ['Use checkboxes for submit-time agreement or selection.', 'Keep labels explicit about what turns on.'],
        examples: ['On/off toggles', 'Left and right alignment', 'Disabled on/off states'],
        tokens: ['--orbit-toggle-*', '--orbit-color-toggle-*'],
      },
    ],
  },
  {
    group: 'Data Display',
    items: [
      {
        id: 'card',
        label: 'Card',
        title: 'Card',
        description: 'Figma-parity content container with explicit shadow, padding, state, and optional indicator rail variants.',
        imports: ['Card', 'CardContent'],
        sourceFiles: ['packages/orbit/src/layout/Card.tsx'],
        whenToUse: ['Use to group related content or frame repeated objects.'],
        guidelines: ['Avoid placing cards inside cards.', 'Use hasShadow for the Figma shadow variant.', 'Use indicator only when the Figma Has Highlight rail is required.'],
        examples: ['Figma state matrix', 'HasShadow true and false', 'Indicator rail on and off', 'ContentPlaceHolder padding and orientation'],
        tokens: ['--orbit-color-card-*', '--orbit-card-indicator-width'],
      },
      {
        id: 'toggle-card',
        label: 'Toggle Card',
        title: 'Toggle Card',
        description: 'Interactive card that acts as a selection control. Wraps a content slot in a bordered container with four distinct states: Default, Hover, Selected, and Disabled.',
        imports: ['ToggleCard'],
        sourceFiles: ['packages/orbit/src/layout/ToggleCard.tsx'],
        whenToUse: ['Use when selection benefits from a rich card-sized presentation rather than a compact checkbox or radio input.', 'Use for plan tier selection, configuration option picking, or content type choosing.', 'Use when the selection area needs to be large and easily tappable.'],
        guidelines: ['ToggleCard does not track its own selection — manage selected state externally via the status prop.', 'Default, Hover, and Selected states render as <button> elements for full keyboard and pointer interactivity.', 'Do not use for read-only content — use Card instead.', 'Do not use for navigation — use Card with an anchor wrapper.'],
        examples: ['All four states: Default, Hover, Selected, Disabled', 'Interactive selection group'],
        tokens: ['--orbit-color-togglecard-*'],
      },
      {
        id: 'table',
        label: 'Table',
        title: 'Table',
        description: 'Tokenised data table with selectable row support.',
        imports: ['Table'],
        sourceFiles: ['packages/orbit/src/layout/Table.tsx'],
        whenToUse: ['Use for structured data that benefits from scanning, sorting, or row selection.'],
        guidelines: ['Use clear column headers.', 'Keep row actions predictable and accessible.'],
        examples: ['Sortable initiative column', 'Selectable rows', 'Pagination controls'],
        tokens: ['--orbit-color-border-*', '--orbit-color-bg-hover'],
      },
      {
        id: 'avatar',
        label: 'Avatar',
        title: 'Avatar',
        description: 'User identity indicator with initials or icon, in multiple sizes.',
        imports: ['Avatar', 'AvatarStack'],
        sourceFiles: ['packages/orbit/src/layout/Avatar.tsx'],
        whenToUse: ['Use to represent people, owners, or collaborators.'],
        guidelines: ['Use accessible names.', 'Use stacks when multiple people share ownership.'],
        examples: ['Extra small, small, medium, and large avatars', 'Text, icon, and square styles', 'Avatar stack with overflow'],
        tokens: ['--orbit-color-bg-*', '--orbit-color-text-*'],
      },
      {
        id: 'status-indicator',
        label: 'Status Indicator',
        title: 'Status Indicator',
        description: 'Coloured dot with label to convey item status at a glance.',
        imports: ['StatusIndicator'],
        sourceFiles: ['packages/orbit/src/indicators/StatusIndicator.tsx'],
        whenToUse: ['Use for compact status labels in lists, tables, and metadata rows.'],
        guidelines: ['Pair colour with text whenever possible.', 'Use no-status when the state is intentionally absent.'],
        examples: ['Success, warning, information, error, and no-status labels'],
        tokens: ['--orbit-color-status-*'],
      },
      {
        id: 'chip',
        label: 'Chip',
        title: 'Chip',
        description: 'Compact label for categorisation, status, or metadata.',
        imports: ['Chip'],
        sourceFiles: ['packages/orbit/src/indicators/Chip.tsx'],
        whenToUse: ['Use for compact metadata, categorisation, or lightweight status labels.'],
        guidelines: ['Use high contrast chips when status must stand out.', 'Use low contrast chips for denser metadata rows.'],
        examples: ['High-contrast chips', 'Low-contrast chips', 'Mini chips'],
        tokens: ['--orbit-color-chip-*', '--orbit-chip-*', '--orbit-color-status-*'],
      },
      {
        id: 'filter',
        label: 'Filter',
        title: 'Filter',
        description: 'Applied-filter pill with optional remove action.',
        imports: ['Filter'],
        sourceFiles: ['packages/orbit/src/indicators/Filter.tsx'],
        whenToUse: ['Use to show active filters that can be removed.'],
        guidelines: ['Use labels that include both filter name and value.', 'Expose remove actions for reversible filters.'],
        examples: ['Default applied filter', 'Hover state applied filter'],
        tokens: ['--orbit-color-border-*', '--orbit-color-bg-hover'],
      },
      {
        id: 'indicators',
        label: 'Indicators',
        title: 'Indicators',
        description: 'Badges, price movement, risk levels, legends, status dots, and radial indicators.',
        imports: ['Badge', 'PriceIndicator', 'RiskIndicator', 'LegendLabel', 'RadialIndicator', 'StepCircle', 'Spinner'],
        sourceFiles: [
          'packages/orbit/src/indicators/Badge.tsx',
          'packages/orbit/src/indicators/PriceIndicator.tsx',
          'packages/orbit/src/indicators/RiskIndicator.tsx',
          'packages/orbit/src/indicators/RadialIndicator.tsx',
          'packages/orbit/src/indicators/StepCircle.tsx',
          'packages/orbit/src/indicators/Spinner.tsx',
        ],
        whenToUse: ['Use when a compact visual signal helps users scan status, progress, or value change.'],
        guidelines: ['Avoid relying on colour alone.', 'Use labels for ambiguous indicators.'],
        examples: ['Number badges', 'Price movement', 'Risk levels', 'Legend labels', 'Status dots', 'Radial indicators', 'Step circles', 'Spinners'],
        tokens: ['--orbit-color-status-*', '--orbit-color-radial-track-*', '--orbit-radial-*'],
      },
      {
        id: 'document-glyph',
        label: 'Document Glyph',
        title: 'Document Glyph',
        description: 'File-type icons at five size tiers for document references.',
        imports: ['DocumentGlyph'],
        sourceFiles: ['packages/orbit/src/indicators/DocumentGlyph.tsx'],
        whenToUse: ['Use to identify file type in document lists, attachments, and upload summaries.'],
        guidelines: ['Pair glyphs with filenames when space allows.', 'Use size tiers consistently within a list.'],
        examples: ['XLS, DOC, PDF, ZIP, IMG, and unknown glyphs from large to micro'],
        tokens: ['--orbit-color-doc-*', '--orbit-document-glyph-*'],
      },
      {
        id: 'file-item',
        label: 'File Item',
        title: 'File Item',
        description: 'Compact selected-file row with document type and truncating filename.',
        imports: ['FileItem'],
        sourceFiles: ['packages/orbit/src/layout/FileItem.tsx'],
        whenToUse: ['Use to represent selected or attached files in forms and document flows.'],
        guidelines: ['Keep filenames visible enough to distinguish similar files.', 'Use document type when known.'],
        examples: ['Fixed-width PDF item', 'XLS item', 'Clickable DOC item'],
        tokens: ['--orbit-color-doc-*', '--orbit-document-glyph-*'],
      },
      {
        id: 'country-flag',
        label: 'Country Flag',
        title: 'Country Flag',
        description: 'ISO country code rendered as a flag icon.',
        imports: ['CountryFlag'],
        sourceFiles: ['packages/orbit/src/layout/CountryFlag.tsx'],
        whenToUse: ['Use when country identity needs to be recognised quickly alongside text.'],
        guidelines: ['Pair with country names in critical contexts.', 'Pass ISO country codes consistently.'],
        examples: ['US, GB, DE, FR, JP, and AU flags'],
        tokens: ['--orbit-color-border-default'],
      },
      {
        id: 'tooltip',
        label: 'Tooltip',
        title: 'Tooltip',
        description: 'Contextual hover popover with directional and aligned placements.',
        imports: ['Tooltip'],
        sourceFiles: ['packages/orbit/src/feedback/Tooltip.tsx'],
        whenToUse: ['Use for short supplemental context on hover or focus.'],
        guidelines: ['Do not put essential workflow content only in a tooltip.', 'Keep tooltip copy brief.'],
        examples: ['Top, bottom, left, and right directions', 'Start and end alignment'],
        tokens: ['--orbit-z-tooltip', '--orbit-color-bg-default', '--orbit-shadow-*'],
      },
    ],
  },
  {
    group: 'Tool Mode',
    items: [
      {
        id: 'tool-next-steps-card',
        label: 'Next Steps Card',
        title: 'Tool Next Steps Card',
        description: 'Compound card for suggested next actions in guided AI tool flows.',
        imports: ['ToolNextStepsCard'],
        sourceFiles: ['packages/orbit/src/tool/ToolNextStepsCard.tsx'],
        whenToUse: ['Use in guided tool experiences to present the next useful action.'],
        guidelines: ["Keep actions relevant to the user's current flow.", 'Avoid using this as a generic marketing card.'],
        examples: ['Default next-steps composition'],
        tokens: ['--orbit-color-card-*', '--orbit-color-btn-*'],
      },
    ],
  },
  {
    group: 'Navigation',
    items: [
      {
        id: 'cp-workspace-shell',
        label: 'CP Workspace Shell',
        title: 'CP Workspace Shell',
        description: 'Live-matched Connected Platform workspace navigation shell with rail, headers, tabs, and milestone timeline.',
        imports: [
          'CpWorkspaceShell',
          'CpSideRail',
          'CpBreadcrumbHeader',
          'CpWorkspaceHeader',
          'CpPrimaryNav',
          'CpSecondaryNav',
          'CpMilestoneTimelineNav',
        ],
        sourceFiles: ['packages/orbit/src/navigation/CpWorkspaceShell.tsx'],
        whenToUse: ['Use for Connected Platform workspace pages that need the Live CP rail, breadcrumb header, primary nav, secondary nav, and milestone timeline.'],
        guidelines: ['Keep CP workspace navigation separate from the Orbit dark SideNav.', 'Use token overrides for Live parity rather than one-off colour or spacing values.'],
        examples: ['Full CP workspace shell', 'Standalone rail', 'Breadcrumb header', 'Primary and secondary navigation', 'Milestone timeline'],
        tokens: ['--orbit-cp-*', '--orbit-color-cp-*'],
      },
      {
        id: 'page-header',
        label: 'Page Header',
        title: 'Page Header',
        description: 'Top-level page headers with titles, actions, tabs, and module presets.',
        imports: ['PageHeader', 'HeaderPresets'],
        sourceFiles: ['packages/orbit/src/navigation/PageHeader.tsx'],
        whenToUse: ['Use at the top of product pages and module surfaces.'],
        guidelines: ['Use presets to keep module identity consistent.', "Keep actions aligned with the page's primary workflow."],
        examples: ['Main headers', 'Headers with CTAs', 'Identify, deliver, sustain, and RFP presets', 'Pills and tabs'],
        tokens: ['--orbit-page-header-*', '--orbit-color-header-*'],
      },
      {
        id: 'side-nav',
        label: 'Side Nav',
        title: 'Side Nav',
        description: 'Application-level sidebar navigation with sections, items, and work history.',
        imports: ['SideNav'],
        sourceFiles: ['packages/orbit/src/navigation/SideNav.tsx'],
        whenToUse: ['Use for persistent application navigation and module grouping.'],
        guidelines: ['Keep top-level destinations stable.', 'Use work items for recent or user-specific entities.'],
        examples: ['Main navigation links', 'Identify/deliver/sustain sections', 'My Work list', 'User profile row'],
        tokens: ['--orbit-sidenav-*', '--orbit-color-sidenav-*'],
      },
      {
        id: 'breadcrumb',
        label: 'Breadcrumb',
        title: 'Breadcrumb',
        description: 'Hierarchical path indicator for nested page navigation.',
        imports: ['Breadcrumb'],
        sourceFiles: ['packages/orbit/src/navigation/Breadcrumb.tsx'],
        whenToUse: ['Use when users are inside nested objects or drill-down pages.'],
        guidelines: ['Keep labels short.', 'Do not replace primary navigation with breadcrumbs.'],
        examples: ['Home / Suppliers / Acme Corp path'],
        tokens: ['--orbit-color-text-secondary', '--orbit-color-border-default'],
      },
      {
        id: 'separator',
        label: 'Separator',
        title: 'Separator',
        description: 'Visual divider in horizontal or vertical orientation.',
        imports: ['Separator'],
        sourceFiles: ['packages/orbit/src/primitives/Separator.tsx'],
        whenToUse: ['Use to separate related content groups without adding a container.'],
        guidelines: ['Prefer whitespace first; use separators when the boundary needs to be explicit.'],
        examples: ['Horizontal divider', 'Vertical divider'],
        tokens: ['--orbit-color-border-default'],
      },
    ],
  },
  {
    group: 'Feedback',
    items: [
      {
        id: 'inline-banner',
        label: 'Inline Banner',
        title: 'Inline Banner',
        description: 'Contextual message bars in high and low contrast styles.',
        imports: ['InlineBanner'],
        sourceFiles: ['packages/orbit/src/feedback/InlineBanner.tsx'],
        whenToUse: ['Use for contextual messages that sit inside the page layout.'],
        guidelines: ['Use high contrast for important status messages.', 'Use low contrast for persistent but lower urgency context.'],
        examples: ['High contrast variants', 'Low contrast variants', 'Neutral and disabled variants'],
        tokens: ['--orbit-inline-banner-*', '--orbit-color-status-*'],
      },
      {
        id: 'alert',
        label: 'Alert Block',
        title: 'Alert Block',
        description: 'Dismissable multiline title and description notifications. Use Inline Banner for the Figma feedback strip.',
        imports: ['Alert'],
        sourceFiles: ['packages/orbit/src/feedback/Alert.tsx'],
        whenToUse: ['Use for larger feedback messages that need title, description, and dismissal.'],
        guidelines: ['Keep descriptions concise.', 'Use the type that matches severity and user action needed.'],
        examples: ['Information, success, error, warning, and no-status alerts'],
        tokens: ['--orbit-color-status-*', '--orbit-color-bg-*'],
      },
      {
        id: 'toast',
        label: 'Toast',
        title: 'Toast',
        description: 'Ephemeral notification messages triggered by user actions.',
        imports: ['Toast'],
        sourceFiles: ['packages/orbit/src/feedback/Toast.tsx'],
        whenToUse: ['Use for temporary confirmation or feedback after an action.'],
        guidelines: ['Do not use toasts for critical information that must persist.', 'Provide actions only when the next step is immediate and obvious.'],
        examples: ['Success, error, info, warning, and no-status toasts', 'Toast with actions'],
        tokens: ['--orbit-toast-max-width', '--orbit-z-toast', '--orbit-color-status-*'],
      },
    ],
  },
];

export const COMPONENT_DOCS: ComponentDoc[] = docsByGroup.flatMap(({ group, items }) =>
  items.map((item) => ({ ...item, group })),
);

export const COMPONENT_SECTION_IDS = COMPONENT_DOCS.map((doc) => doc.id);

export const COMPONENT_NAV_GROUPS: DesignSystemNavGroup[] = docsByGroup.map(({ group, items }) => ({
  group,
  items: items.map(({ label, id }) => ({ label, id })),
}));

export function getComponentNavGroups(mode: 'hash' | 'routes'): DesignSystemNavGroup[] {
  return COMPONENT_NAV_GROUPS.map((group) => ({
    ...group,
    items: group.items.map((item) => ({
      ...item,
      href: mode === 'routes' ? `/design-system/components/${item.id}` : `#${item.id}`,
    })),
  }));
}

export function getComponentDoc(id: string) {
  return COMPONENT_DOCS.find((doc) => doc.id === id);
}
