#!/usr/bin/env node
/**
 * build-skills.ts
 *
 * Generates the Orbit Claude Code skills under `.claude/skills/` from the same
 * token source `build-design-md.ts` reads, plus hand-authored prose partials in
 * `design-md/prose/skills/`. Skills are project-level, committed, and picked up
 * by Claude Code with no restart.
 *
 * Skills emitted:
 *   orbit-tokens        — every design token + how to reference it   (this phase)
 *   orbit-foundations   — principles, voice, do/don'ts               (later phase)
 *   orbit-a11y          — accessibility + quality contracts          (later phase)
 *   orbit-components    — 54-component API surface                   (later phase)
 *
 * Usage:
 *   npm run build:skills                 Regenerate all skills
 *   npm run build:skills -- --check      Fail if any skill is out of date
 *   npm run build:skills -- --skip-figma Accepted for parity; no-op here
 *
 * Data-heavy reference files are GENERATED from source; editorial prose lives in
 * design-md/prose/skills/*.md and is concatenated in. Never edit generated files
 * by hand — edit the token source or the prose partial and re-run.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import { detectTokenSource, loadTokens, type Tokens } from './lib/load-tokens';
import { extractComponents, emitComponent, type ComponentInfo } from './lib/extract-components';
import { parseAuditChecks } from './lib/audit-checks';

const REPO_ROOT = resolve(process.cwd());
const SKILLS_DIR = join(REPO_ROOT, '.claude', 'skills');

const args = process.argv.slice(2);
const CHECK_MODE = args.includes('--check');

const GEN_BANNER =
  '<!-- GENERATED by scripts/build-skills.ts — do not edit by hand. ' +
  'Edit the token source or design-md/prose/skills/, then run `npm run build:skills`. -->';

interface OutFile {
  /** Path relative to SKILLS_DIR. */
  rel: string;
  content: string;
}

// ── Small formatting helpers ─────────────────────────────────────────────────

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map(r => `| ${r.map(cell => cell.replace(/\|/g, '\\|')).join(' | ')} |`).join('\n');
  return `${head}\n${sep}\n${body}`;
}

function code(s: string): string {
  return '`' + s + '`';
}

/** Resolve a single `var(--orbit-…)` reference against a stripped-name lookup. */
function resolveVar(value: string | number, lookup: Record<string, string | number>): string {
  const s = String(value);
  const m = s.match(/^var\(--orbit-([\w-]+)\)$/);
  if (m) {
    const key = m[1];
    if (key in lookup) return String(lookup[key]);
  }
  return s;
}

// ── orbit-tokens skill ───────────────────────────────────────────────────────

const ORBIT_TOKENS_DESCRIPTION =
  "Design tokens for Orbit, Efficio's procurement-intelligence design system. " +
  'Use whenever choosing, applying, or verifying any colour, spacing, font or ' +
  'typography, border-radius, shadow/elevation, or z-index value in Orbit or ' +
  '@efficio/orbit UI — including converting a raw hex to its token, checking the ' +
  'spacing scale, or referencing a semantic colour (text, border, background). ' +
  'Tokens are CSS custom properties (--orbit-…); never hard-code raw values. ' +
  'Orbit is light-only (no dark mode); the base/CP palette is canonical and the ' +
  'data-theme="orbit" brand variant is documented separately in references/theme-orbit.md. ' +
  'For component props and variants use the orbit-components skill; for design ' +
  'principles and do/don\'ts use orbit-foundations; for accessibility use orbit-a11y.';

function buildOrbitTokensSkill(tokens: Tokens): OutFile[] {
  const files: OutFile[] = [];

  // Lookups for resolving var() references in nested token values.
  const spacingLookup: Record<string, string | number> = {};
  for (const [k, v] of Object.entries(tokens.spacing)) spacingLookup[`space-${k}`] = v;
  const typoVars = tokens.components?.typography ?? {};

  // ---- SKILL.md ----
  const colorCount = Object.keys(tokens.colors).length;
  const skill = `---
name: orbit-tokens
description: ${ORBIT_TOKENS_DESCRIPTION}
---
${GEN_BANNER}

# Orbit tokens

Orbit is Efficio's design system for AI-orchestrated procurement intelligence. This
skill is the authoritative source for Orbit's **design tokens** — the exact colour,
spacing, typography, radius, and elevation values, and the rules for referencing them.

## How to reference tokens

- Tokens are **CSS custom properties** prefixed \`--orbit-\`. Reference them with
  \`var(--orbit-…)\` (or, in \`DESIGN.md\` YAML, \`{colors.token}\`).
- **Never hard-code a raw value** (hex, px, etc.) in a reusable component — the
  static audit (\`npm run audit:design-system\`) fails on raw hex in
  \`packages/orbit/src\`. Reach for the semantic token first, then the primitive.
- Prefer **semantic** colour tokens (\`text-*\`, \`border-*\`, \`bg-*\`) over primitives
  for anything that conveys meaning; primitives are the underlying palette.

## Theme

Orbit is **light-only — there is no dark mode.** The base \`:root\` palette ("CP
mode") is **canonical**. A single brand variant, **Orbit mode**, is activated by
\`data-theme="orbit"\` on an ancestor and re-skins some colours; it is a re-skin, not
a light/dark toggle. Its overrides are documented in \`references/theme-orbit.md\`.

## Token groups (load the reference you need)

- **Colours** (${colorCount} tokens: primitives + semantic) → \`references/colors.md\`
- **Spacing** scale (numeric + named \`none\`→\`mega\`) → \`references/spacing.md\`
- **Typography** (families, sizes, weights, leadings, composite text styles) → \`references/typography.md\`
- **Radius, shadow, z-index, focus ring** → \`references/radius-elevation.md\`
- **Orbit-mode brand overrides** → \`references/theme-orbit.md\`
`;
  files.push({ rel: 'orbit-tokens/SKILL.md', content: skill });

  // ---- references/colors.md ----
  const semanticKeys: string[] = [];
  const primitiveKeys: string[] = [];
  for (const key of Object.keys(tokens.colors)) {
    if (/^(text|border|bg)-/.test(key)) semanticKeys.push(key);
    else primitiveKeys.push(key);
  }
  const role = (k: string): string =>
    k.startsWith('text-') ? 'Text' : k.startsWith('border-') ? 'Border' : k.startsWith('bg-') ? 'Background' : '';
  const semanticRows = semanticKeys.map(k => [code(k), code(`var(--orbit-color-${k})`), tokens.colors[k], role(k)]);
  const primitiveRows = primitiveKeys.map(k => [code(k), code(`var(--orbit-color-${k})`), tokens.colors[k]]);

  const colorsMd = `${GEN_BANNER}

# Orbit colours

Canonical **CP/base** palette (Orbit is light-only). Reference via
\`var(--orbit-color-<token>)\` — never a raw hex. Orbit-mode overrides are in
\`theme-orbit.md\`.

## Semantic colours

Use these for anything meaningful. They alias the primitives below.

${table(['Token', 'CSS variable', 'Value', 'Role'], semanticRows)}

## Primitive palette

The underlying ramp. Prefer a semantic token; use a primitive only when no semantic
token fits.

${table(['Name', 'CSS variable', 'Value'], primitiveRows)}
`;
  files.push({ rel: 'orbit-tokens/references/colors.md', content: colorsMd });

  // ---- references/spacing.md ----
  const numericKeys = Object.keys(tokens.spacing).filter(k => !String(tokens.spacing[k]).startsWith('var('));
  const aliasKeys = Object.keys(tokens.spacing).filter(k => String(tokens.spacing[k]).startsWith('var('));
  const numericRows = numericKeys.map(k => [code(k), String(tokens.spacing[k]), code(`var(--orbit-space-${k})`)]);
  const aliasRows = aliasKeys.map(k => {
    const resolved = resolveVar(tokens.spacing[k], spacingLookup);
    const refMatch = String(tokens.spacing[k]).match(/^var\(--orbit-space-([\w-]+)\)$/);
    const refKey = refMatch ? refMatch[1] : '';
    return [code(k), resolved, code(`var(--orbit-space-${k})`), refKey ? code(refKey) : ''];
  });

  const spacingMd = `${GEN_BANNER}

# Orbit spacing

A single spacing scale, exposed twice: bare numeric steps and named aliases that
point at them. Use the **named aliases** in components for intent
(\`var(--orbit-space-base)\`), the numeric steps when a specific value is needed.

## Scale

${table(['Step', 'Value', 'CSS variable'], numericRows)}

## Named aliases

${table(['Alias', 'Value', 'CSS variable', 'Maps to step'], aliasRows)}
`;
  files.push({ rel: 'orbit-tokens/references/spacing.md', content: spacingMd });

  // ---- references/typography.md ----
  const families = Object.entries(typoVars).filter(([k]) => k.startsWith('font-family-'));
  const sizes = Object.entries(typoVars).filter(([k]) => /^text-(xs|sm|base|lg|xl|2xl|3xl)$/.test(k));
  const weights = Object.entries(typoVars).filter(([k]) => k.startsWith('font-weight-'));
  const leadings = Object.entries(typoVars).filter(([k]) => k.startsWith('leading-'));

  const styleRows = Object.entries(tokens.typography).map(([name, t]) => [
    code(name),
    resolveVar(t.fontFamily, typoVars),
    resolveVar(t.fontSize, typoVars),
    resolveVar(t.fontWeight, typoVars),
    resolveVar(t.lineHeight, typoVars),
  ]);

  const typographyMd = `${GEN_BANNER}

# Orbit typography

Two families: a workhorse sans (Inter) for UI and a brand face (Sofia Pro) for
display moments. Sizes, weights, and line-heights are tokenised; composite text
styles bundle them per role.

## Font families

${table(['Token', 'Value'], families.map(([k, v]) => [code(`--orbit-${k}`), String(v)]))}

## Sizes

${table(['Token', 'Value'], sizes.map(([k, v]) => [code(`--orbit-${k}`), String(v)]))}

## Weights

${table(['Token', 'Value'], weights.map(([k, v]) => [code(`--orbit-${k}`), String(v)]))}

## Line heights

${table(['Token', 'Value'], leadings.map(([k, v]) => [code(`--orbit-${k}`), String(v)]))}

## Composite text styles

Resolved values shown for convenience; in code these are token references.

${table(['Style', 'Family', 'Size', 'Weight', 'Line height'], styleRows)}
`;
  files.push({ rel: 'orbit-tokens/references/typography.md', content: typographyMd });

  // ---- references/radius-elevation.md ----
  const elevation = tokens.components?.elevation ?? {};
  const radiusRows = Object.entries(tokens.rounded).map(([k, v]) => [code(k), String(v), code(`var(--orbit-radius-${k})`)]);
  const shadowRows = Object.entries(elevation)
    .filter(([k]) => k.startsWith('shadow-'))
    .map(([k, v]) => [code(`--orbit-${k}`), String(v)]);
  const zRows = Object.entries(elevation)
    .filter(([k]) => k.startsWith('z-'))
    .map(([k, v]) => [code(`--orbit-${k}`), String(v)]);
  const focusRows = Object.entries(elevation)
    .filter(([k]) => k.includes('focus'))
    .map(([k, v]) => [code(`--orbit-${k}`), String(v)]);

  const radiusElevationMd = `${GEN_BANNER}

# Orbit radius & elevation

Orbit is a **mostly flat** system: hierarchy comes from tonal layering and borders,
not shadow. Shadows are reserved for genuinely floating UI (dropdowns, popovers,
tooltips, modals, toasts).

## Border radius

${table(['Token', 'Value', 'CSS variable'], radiusRows)}

> ⚠ **Known gap:** \`rounded.full\` / \`--orbit-radius-pill\` is referenced by 6
> components (Avatar, Filter, StepCircle, SideNav, Radio, MultiSelectDropdown) but
> is **not defined** in the token source. Until a \`--orbit-radius-pill\` token is
> added, those components rely on a CSS fallback. Do not invent a value — treat
> "full/pill" as an undefined token pending a fix.

## Shadows

${table(['Token', 'Value'], shadowRows)}

## Z-index

${table(['Token', 'Value'], zRows)}

## Focus ring

${focusRows.length ? table(['Token', 'Value'], focusRows) : '_(none)_'}
`;
  files.push({ rel: 'orbit-tokens/references/radius-elevation.md', content: radiusElevationMd });

  // ---- references/theme-orbit.md ----
  // Build a base-value lookup spanning every token group so override base
  // values resolve whether they live in colors, components, typography, etc.
  const baseLookup: Record<string, string> = {};
  for (const [k, v] of Object.entries(tokens.colors)) {
    baseLookup[`color-${k}`] = String(v);
    baseLookup[k] = String(v);
  }
  for (const group of Object.values(tokens.components ?? {})) {
    for (const [k, v] of Object.entries(group)) {
      if (!(k in baseLookup)) baseLookup[k] = String(v);
    }
  }

  const overrides = tokens.themeOverrides ?? {};
  const colorOverrideKeys = Object.keys(overrides).filter(k => k.startsWith('color-'));
  const otherOverrideKeys = Object.keys(overrides).filter(k => !k.startsWith('color-'));

  const colorOverrideRows = colorOverrideKeys.map(k => {
    const name = k.replace(/^color-/, '');
    const base = baseLookup[k] ?? baseLookup[name] ?? '—';
    return [code(name), code(`var(--orbit-color-${name})`), base, String(overrides[k])];
  });
  const otherOverrideRows = otherOverrideKeys.map(k => {
    const base = baseLookup[k] ?? '—';
    return [code(`--orbit-${k}`), base, String(overrides[k])];
  });

  const themeOrbitMd = `${GEN_BANNER}

# Orbit mode (brand variant)

**This is a re-skin, NOT a dark mode.** Orbit is light-only. "Orbit mode" is an
alternative theme from Figma activated by \`data-theme="orbit"\` on an ancestor
element; the prototypes render under it. It overrides a subset of tokens
(saturated status/semantic foregrounds, heading weight, some chrome sizing) on top
of the canonical **CP/base** palette. When the theme is **not** active, the CP/base
values apply.

The base (CP) value is canonical; the tables show what each token becomes under
Orbit mode.

## Colour overrides

${colorOverrideRows.length ? table(['Token', 'CSS variable', 'CP/base value', 'Orbit-mode value'], colorOverrideRows) : '_(none)_'}

## Non-colour overrides (typography & chrome)

${otherOverrideRows.length ? table(['CSS variable', 'CP/base value', 'Orbit-mode value'], otherOverrideRows) : '_(none)_'}
`;
  files.push({ rel: 'orbit-tokens/references/theme-orbit.md', content: themeOrbitMd });

  return files;
}

// ── Source readers ───────────────────────────────────────────────────────────

function readRepo(rel: string): string {
  return readFileSync(join(REPO_ROOT, rel), 'utf-8');
}
function readRepoSafe(rel: string): string {
  const abs = join(REPO_ROOT, rel);
  return existsSync(abs) ? readFileSync(abs, 'utf-8') : '';
}

/** Count exported component categories (src subdirs with an index.ts) and the
 *  total component count from the generated manifest. */
function componentStats(): { count: number; categories: string[] } {
  const srcDir = join(REPO_ROOT, 'packages', 'orbit', 'src');
  const categories = existsSync(srcDir)
    ? readdirSync(srcDir).filter(d => {
        try {
          return statSync(join(srcDir, d)).isDirectory() && existsSync(join(srcDir, d, 'index.ts'));
        } catch {
          return false;
        }
      })
    : [];
  const manifest = readRepoSafe('orbit-manifest.md');
  const m = manifest.match(/Total component count:\**\s*(\d+)/);
  const count = m ? parseInt(m[1], 10) : 0;
  return { count, categories };
}

// ── orbit-foundations skill ────────────────────────────────────────────────

const ORBIT_FOUNDATIONS_DESCRIPTION =
  "Core design principles, visual philosophy, and usage rules (do's and don'ts) for " +
  "Orbit, Efficio's procurement-intelligence design system. Use whenever building, " +
  'reviewing, or discussing any Orbit or Efficio app UI and you need the "why": how ' +
  'Orbit handles colour hierarchy and the single primary action, typography and ' +
  'density, elevation/depth (mostly-flat, tonal layering over shadow), shape language, ' +
  'and marking AI-authored surfaces distinctly. Orbit is light-only — no dark mode. ' +
  'Consult this before the other orbit-* skills for any non-trivial Orbit design ' +
  'decision. For exact token values use orbit-tokens; for component APIs use ' +
  'orbit-components; for accessibility contracts use orbit-a11y.';

function buildOrbitFoundationsSkill(tokens: Tokens): OutFile[] {
  const files: OutFile[] = [];
  const { count, categories } = componentStats();
  const colorCount = Object.keys(tokens.colors).length;
  const spacingCount = Object.keys(tokens.spacing).length;
  const radiusCount = Object.keys(tokens.rounded).length;
  const styleCount = Object.keys(tokens.typography).length;

  // Prose is generated from the canonical editorial source so it never drifts.
  const prose = readRepo('design-md/prose/DESIGN.prose.md');
  const overviewIdx = prose.indexOf('## Overview');
  const proseBody = overviewIdx >= 0 ? prose.slice(overviewIdx).trimEnd() : prose.trimEnd();

  // ---- references/at-a-glance.md ----
  const atAGlance = `${GEN_BANNER}

# Orbit at a glance

| Aspect | Value |
| --- | --- |
| System | Orbit — Efficio's design system for AI-orchestrated procurement intelligence |
| Components | ${count} across ${categories.length} categories: ${categories.join(', ')} |
| Colour tokens | ${colorCount} (primitives + semantic) |
| Spacing | ${spacingCount} steps (numeric + named aliases) |
| Border radius | ${radiusCount} steps |
| Type styles | ${styleCount} composite text styles |
| Theme | Light-only. Base/CP palette is canonical; \`data-theme="orbit"\` is a brand re-skin, not a dark mode |
| Personality | Considered, precise, quietly confident — not playful, not minimalist for its own sake |

Exact values live in the **orbit-tokens** skill; component APIs in **orbit-components**;
accessibility contracts in **orbit-a11y**.
`;
  files.push({ rel: 'orbit-foundations/references/at-a-glance.md', content: atAGlance });

  // ---- SKILL.md ----
  const skill = `---
name: orbit-foundations
description: ${ORBIT_FOUNDATIONS_DESCRIPTION}
---
${GEN_BANNER}

# Orbit foundations

This skill carries Orbit's **design principles, voice, and do's & don'ts** — the
reasoning behind the system. It does not list token values or component props:

- Exact token values → **orbit-tokens** skill
- Component APIs, variants, props → **orbit-components** skill
- Accessibility & quality contracts → **orbit-a11y** skill

Orbit is **light-only (no dark mode)**. The base/CP palette is canonical; the
\`data-theme="orbit"\` variant is a brand re-skin. See \`references/at-a-glance.md\` for
the system summary and counts.

${proseBody}
`;
  files.push({ rel: 'orbit-foundations/SKILL.md', content: skill });

  return files;
}

// ── orbit-a11y skill ─────────────────────────────────────────────────────────

const ORBIT_A11Y_DESCRIPTION =
  "Accessibility and design-system quality contracts for Orbit, Efficio's design " +
  'system. Use whenever building or reviewing Orbit or @efficio/orbit UI for ' +
  'accessibility — accessible names for inputs (Input, Textbox, TextArea, ' +
  'CurrencyInput, DateInput, Searchbox, Dropdown), native checkbox/switch semantics, ' +
  'dialog naming and focus restoration for overlays, non-interactive cards, labelled ' +
  'vs decorative spinners, no raw hex in reusable components, token-owned sizing, and ' +
  'WCAG 2.2 AA contrast (4.5:1 text, 3:1 large/UI). These are enforced by the static ' +
  'audit — run `npm run audit:design-system` to verify. For tokens use orbit-tokens; ' +
  'for component APIs use orbit-components; for principles use orbit-foundations.';

function buildOrbitA11ySkill(): OutFile[] {
  const files: OutFile[] = [];
  const checks = parseAuditChecks();
  const a11yNotes = readRepoSafe('design-md/prose/skills/a11y.notes.md').trimEnd();

  // ---- references/audit-checks.md ----
  const checkRows = checks.map((c, i) => [String(i + 1), c.name, c.details || '—']);
  const auditChecksMd = `${GEN_BANNER}

# Orbit audit checklist

Every contract below is **machine-enforced** by \`scripts/design-system-static-audit.mjs\`.
Run \`npm run audit:design-system\` to verify a change against them. Use this list when
reviewing or building Orbit UI; treat each row as a must-pass.

${table(['#', 'Contract', 'Remediation if it fails'], checkRows)}

_${checks.length} checks. Generated from the audit script — if you add a check there,
re-run \`npm run build:skills\` to update this list._
`;
  files.push({ rel: 'orbit-a11y/references/audit-checks.md', content: auditChecksMd });

  // ---- references/input-naming-contract.md ----
  const inputNamingMd = `${GEN_BANNER}

# Input accessible-name contract

Every Orbit input requires a deliberate accessible name. Two prop shapes enforce this
at the type level (from \`packages/orbit/src/inputs/naming.ts\`):

## \`FieldNamingProps\` — components with a visible label

A visible \`label\`, **or** \`ariaLabel\`, **or** \`ariaLabelledBy\` is required (at least one):

\`\`\`ts
type FieldNamingProps =
  | { label: string; ariaLabel?: string; ariaLabelledBy?: string }
  | { label?: undefined; ariaLabel: string; ariaLabelledBy?: string }
  | { label?: undefined; ariaLabel?: string; ariaLabelledBy: string };
\`\`\`

Used by: **Input, Textbox, TextArea, CurrencyInput, Dropdown**.

## \`StandaloneFieldNamingProps\` — components without a visible label

\`ariaLabel\` **or** \`ariaLabelledBy\` is required:

\`\`\`ts
type StandaloneFieldNamingProps =
  | { ariaLabel: string; ariaLabelledBy?: string }
  | { ariaLabel?: string; ariaLabelledBy: string };
\`\`\`

Used by: **DateInput, Searchbox** (and the standalone path of Input).

## Enforcement

- The type unions make an unnamed field a **compile error**.
- The dev-only \`warnIfUnnamed(componentName, label, ariaLabel, ariaLabelledBy)\` helper
  logs a console warning if a field renders with no accessible name.
- The static audit asserts the contract is wired across the input family
  (\`npm run audit:design-system\`).
`;
  files.push({ rel: 'orbit-a11y/references/input-naming-contract.md', content: inputNamingMd });

  // ---- SKILL.md ----
  const skill = `---
name: orbit-a11y
description: ${ORBIT_A11Y_DESCRIPTION}
---
${GEN_BANNER}

# Orbit accessibility & quality

Orbit ships accessibility as **enforced contracts**, not aspirations. ${checks.length}
of them are checked by \`scripts/design-system-static-audit.mjs\`; run
\`npm run audit:design-system\` before sharing component changes.

- The full machine-enforced checklist → \`references/audit-checks.md\`
- The input accessible-name contract → \`references/input-naming-contract.md\`

${a11yNotes}
`;
  files.push({ rel: 'orbit-a11y/SKILL.md', content: skill });

  return files;
}

// ── orbit-components skill ────────────────────────────────────────────────

const ORBIT_COMPONENTS_DESCRIPTION =
  'API reference for the Orbit React components (@efficio/orbit) across primitives, ' +
  'actions, inputs, feedback, indicators, navigation, layout, and tool — Button, Input, ' +
  'Dropdown, Checkbox, Toggle, Table, Card, Alert, Toast, Tooltip, Overlay, Badge, Chip, ' +
  'SideNav, Breadcrumb, Avatar, and more. Use whenever importing, configuring, or ' +
  'composing an Orbit or @efficio/orbit component: choosing a variant, looking up prop ' +
  'names/types/defaults, finding which tokens a component consumes, or deciding which ' +
  'primitive to compose. Reach for this when writing JSX that renders Orbit components ' +
  'or wiring an Efficio prototype screen. For token values use orbit-tokens; for ' +
  'accessibility contracts use orbit-a11y; for design principles use orbit-foundations.';

const CATEGORY_TITLES: Record<string, string> = {
  primitives: 'Primitives',
  actions: 'Actions',
  inputs: 'Inputs',
  feedback: 'Feedback',
  indicators: 'Indicators',
  navigation: 'Navigation',
  layout: 'Layout',
  tool: 'Tool',
};

function buildOrbitComponentsSkill(): OutFile[] {
  const files: OutFile[] = [];
  const components = extractComponents();

  // Group by category, preserving a stable category order.
  const byCategory = new Map<string, ComponentInfo[]>();
  for (const c of components) {
    if (!byCategory.has(c.category)) byCategory.set(c.category, []);
    byCategory.get(c.category)!.push(c);
  }
  const categoryOrder = Object.keys(CATEGORY_TITLES).filter(c => byCategory.has(c));
  for (const c of byCategory.keys()) if (!categoryOrder.includes(c)) categoryOrder.push(c);

  // ---- SKILL.md (index) ----
  const indexSections = categoryOrder.map(cat => {
    const title = CATEGORY_TITLES[cat] ?? cat;
    const rows = byCategory.get(cat)!.map(c => [code(c.name), c.description || '—']);
    return `### ${title}\n\nSee \`references/${cat}.md\` for full props.\n\n${table(['Component', 'Description'], rows)}`;
  });

  const skill = `---
name: orbit-components
description: ${ORBIT_COMPONENTS_DESCRIPTION}
---
${GEN_BANNER}

# Orbit components

${components.length} React components across ${categoryOrder.length} categories. Import everything
from the package boundary:

\`\`\`tsx
import { Button, Card, Input } from '@efficio/orbit';
import type { ButtonProps } from '@efficio/orbit';
\`\`\`

## Rules

- Import Orbit UI from \`@efficio/orbit\`, never from a local copy.
- **Compound components compose primitives — they never redefine token values.**
  If you need a new value, add a token (see orbit-tokens), don't hard-code it.
- Props are fully typed; the per-category reference files below list every prop,
  its type, whether it's required, and its default. Token values live in the
  **orbit-tokens** skill; accessibility contracts in **orbit-a11y**.

## Index

${indexSections.join('\n\n')}
`;
  files.push({ rel: 'orbit-components/SKILL.md', content: skill });

  // ---- references/<category>.md ----
  for (const cat of categoryOrder) {
    const title = CATEGORY_TITLES[cat] ?? cat;
    const blocks = byCategory.get(cat)!.map(emitComponent).join('\n\n');
    const content = `${GEN_BANNER}

# Orbit ${title.toLowerCase()} components

Full API for the **${title}** category. Import from \`@efficio/orbit\`. Token values are
in the orbit-tokens skill; accessibility contracts in orbit-a11y.

${blocks}
`;
    files.push({ rel: `orbit-components/references/${cat}.md`, content });
  }

  return files;
}

// ── Orchestration ────────────────────────────────────────────────────────────

function collectAllFiles(tokens: Tokens): OutFile[] {
  return [
    ...buildOrbitTokensSkill(tokens),
    ...buildOrbitFoundationsSkill(tokens),
    ...buildOrbitA11ySkill(),
    ...buildOrbitComponentsSkill(),
  ];
}

function writeFiles(files: OutFile[]): void {
  for (const f of files) {
    const abs = join(SKILLS_DIR, f.rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, f.content);
    console.log(`  ✓ ${join('.claude/skills', f.rel)}`);
  }
}

function checkFiles(files: OutFile[]): string[] {
  const drift: string[] = [];
  for (const f of files) {
    const abs = join(SKILLS_DIR, f.rel);
    const existing = existsSync(abs) ? readFileSync(abs, 'utf-8') : '';
    if (existing.trim() !== f.content.trim()) {
      drift.push(join('.claude/skills', f.rel));
    }
  }
  return drift;
}

(async () => {
  console.log('▶ Building Orbit skills\n');

  const source = detectTokenSource();
  const tokens = loadTokens(source);
  console.log(`  Loaded ${Object.keys(tokens.colors).length} colors, ` +
              `${Object.keys(tokens.spacing).length} spacing, ` +
              `${Object.keys(tokens.rounded).length} radius, ` +
              `${Object.keys(tokens.themeOverrides ?? {}).length} theme overrides\n`);

  const files = collectAllFiles(tokens);

  if (CHECK_MODE) {
    const drift = checkFiles(files);
    if (drift.length > 0) {
      console.error(`\n✗ ${drift.length} skill file(s) out of date. Run \`npm run build:skills\`:`);
      for (const d of drift) console.error(`  • ${d}`);
      process.exit(1);
    }
    console.log('\n✓ All skill files up to date');
    return;
  }

  writeFiles(files);
  console.log(`\n✓ Wrote ${files.length} skill file(s) to .claude/skills/`);
})();
