#!/usr/bin/env node
/**
 * build-docs-data.ts
 *
 * Emits the data module the docs app reads to render per-component pages:
 *   apps/docs/app/design-system/_generated/component-data.ts
 *
 * Reuses the shared extractors (no new extraction):
 *   - extractComponents()  → props/variants/tokens/composes (from packages/orbit/src)
 *   - parseAuditChecks()   → the static-audit contracts (for per-component a11y notes)
 *
 * Adds per component: slug, categoryTitle, usedBy (inverted composes), a11y (matched
 * contracts), and inlined usage (from design-md/prose/components/<slug>.md, seeded
 * if missing — never overwritten).
 *
 * Usage:
 *   npm run build:docs-data              Regenerate the module (seeds missing usage files)
 *   npm run build:docs-data -- --check   Fail if the module is out of date
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, join, dirname } from 'node:path';
import { extractComponents, type ComponentInfo } from './lib/extract-components';
import { parseAuditChecks } from './lib/audit-checks';

const REPO_ROOT = resolve(process.cwd());
const OUTPUT = join(REPO_ROOT, 'apps', 'docs', 'app', 'design-system', '_generated', 'component-data.ts');
const USAGE_DIR = join(REPO_ROOT, 'design-md', 'prose', 'components');
const CHECK_MODE = process.argv.slice(2).includes('--check');

const CATEGORY_TITLES: Record<string, string> = {
  primitives: 'Primitives',
  actions: 'Actions',
  inputs: 'Inputs',
  feedback: 'Feedback',
  indicators: 'Indicators',
  navigation: 'Navigation',
  layout: 'Layout',
  tool: 'Tool',
};
const CATEGORY_ORDER = Object.keys(CATEGORY_TITLES);

interface DocComponent extends ComponentInfo {
  slug: string;
  categoryTitle: string;
  importName: string;
  usedBy: string[];
  a11y: { name: string; details: string }[];
  usage: string;
}

function slugify(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function usageStub(c: ComponentInfo): string {
  return `<!-- Usage guidance for ${c.name}. Editable — author freely, then run \`npm run build:docs-data\`. -->

${c.description || c.name + '.'}

<!-- TODO: when to use ${c.name}, and the do's & don'ts. -->
`;
}

/** Read a component's usage file; seed a stub if missing (never overwrites). */
function loadUsage(c: ComponentInfo, slug: string): string {
  const path = join(USAGE_DIR, `${slug}.md`);
  if (!existsSync(path)) {
    if (!CHECK_MODE) {
      mkdirSync(USAGE_DIR, { recursive: true });
      writeFileSync(path, usageStub(c));
    } else {
      return ''; // --check: don't create files; empty will surface as drift
    }
  }
  return readFileSync(path, 'utf-8').trimEnd();
}

function buildDocComponents(): DocComponent[] {
  const components = extractComponents();
  const checks = parseAuditChecks();

  // Invert composes → usedBy.
  const usedBy: Record<string, string[]> = {};
  for (const c of components) {
    for (const dep of c.composes) (usedBy[dep] ??= []).push(c.name);
  }

  // slug uniqueness guard.
  const seenSlugs = new Set<string>();

  return components.map(c => {
    const slug = slugify(c.name);
    if (seenSlugs.has(slug)) throw new Error(`Duplicate slug "${slug}" for component ${c.name}`);
    seenSlugs.add(slug);

    // a11y: contracts that mention this component by PascalCase word boundary.
    const re = new RegExp(`\\b${c.name}\\b`);
    const a11y = checks.filter(chk => re.test(`${chk.name} ${chk.details}`));

    return {
      ...c,
      slug,
      categoryTitle: CATEGORY_TITLES[c.category] ?? c.category,
      importName: c.name,
      usedBy: (usedBy[c.name] ?? []).sort(),
      a11y,
      usage: loadUsage(c, slug),
    };
  });
}

function emitModule(docs: DocComponent[]): string {
  return `// GENERATED by scripts/build-docs-data.ts — do not edit by hand.
// Reference (props/variants/tokens/composes) is extracted from packages/orbit/src.
// Descriptions come from design-md/prose/skills/component-descriptions.md; usage from
// design-md/prose/components/<slug>.md. Run \`npm run build:docs-data\` to regenerate.

export interface DocPropInfo { name: string; type: string; required: string; default: string }
export interface DocAudit { name: string; details: string }
export interface DocComponent {
  name: string;
  slug: string;
  category: string;
  categoryTitle: string;
  description: string;
  importName: string;
  file: string;
  props: DocPropInfo[];
  variants: { prop: string; values: string[] }[];
  tokens: Record<string, string[]>;
  composes: string[];
  usedBy: string[];
  a11y: DocAudit[];
  usage: string;
}

export const CATEGORY_ORDER: string[] = ${JSON.stringify(CATEGORY_ORDER)};
export const CATEGORY_TITLES: Record<string, string> = ${JSON.stringify(CATEGORY_TITLES, null, 2)};

export const COMPONENTS: DocComponent[] = ${JSON.stringify(docs, null, 2)};

export const BY_SLUG: Record<string, DocComponent> = Object.fromEntries(
  COMPONENTS.map((c) => [c.slug, c]),
);

export const NAV: { category: string; title: string; items: { name: string; slug: string }[] }[] =
  CATEGORY_ORDER.filter((cat) => COMPONENTS.some((c) => c.category === cat)).map((cat) => ({
    category: cat,
    title: CATEGORY_TITLES[cat] ?? cat,
    items: COMPONENTS.filter((c) => c.category === cat).map((c) => ({ name: c.name, slug: c.slug })),
  }));
`;
}

const output = emitModule(buildDocComponents());

if (CHECK_MODE) {
  const existing = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf-8') : '';
  if (existing.trim() !== output.trim()) {
    console.error('✗ component-data.ts is out of date. Run `npm run build:docs-data`.');
    process.exit(1);
  }
  console.log('✓ component-data.ts is up to date');
} else {
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, output);
  console.log(`✓ Wrote ${OUTPUT.replace(REPO_ROOT + '/', '')}`);
}
