#!/usr/bin/env node
/**
 * build-manifest.ts
 *
 * Regenerates orbit-manifest.md FROM SOURCE. The heavy lifting (TypeScript
 * compiler API extraction of props/variants/tokens/composes) lives in
 * scripts/lib/extract-components.ts and is shared with build-skills.ts, so the
 * manifest and the orbit-components skill can never disagree.
 *
 * Descriptions are not derivable from source (components carry no JSDoc); they
 * come from the editable sidecar design-md/prose/skills/component-descriptions.md.
 *
 * Usage:
 *   npm run build:manifest                Regenerate orbit-manifest.md
 *   npm run build:manifest -- --check     Fail if orbit-manifest.md is out of date
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { extractComponents, emitComponent, type ComponentInfo } from './lib/extract-components';

const REPO_ROOT = resolve(process.cwd());
const OUTPUT = join(REPO_ROOT, 'orbit-manifest.md');
const CHECK_MODE = process.argv.slice(2).includes('--check');

function buildManifest(components: ComponentInfo[]): string {
  const noDocs = components.filter(c => !c.description).map(c => c.name);
  const header = [
    '# Orbit Component Manifest',
    '',
    '<!-- GENERATED by scripts/build-manifest.ts from packages/orbit/src — do not edit by hand.',
    'Props, variants, tokens, and composition are extracted from source via the TypeScript',
    'compiler API. Descriptions come from design-md/prose/skills/component-descriptions.md.',
    'Run `npm run build:manifest` to regenerate. -->',
    '',
    'Source scanned: `packages/orbit/src`.',
    '',
  ].join('\n');
  const body = components.map(emitComponent).join('\n\n');
  const stats = [
    '',
    '',
    '## Manifest Stats',
    `- **Total component count:** ${components.length}`,
    `- **Components without a description:** ${noDocs.length ? noDocs.map(n => `\`${n}\``).join(', ') : 'none'}`,
  ].join('\n');
  return header + body + stats + '\n';
}

const output = buildManifest(extractComponents());

if (CHECK_MODE) {
  const existing = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf-8') : '';
  if (existing.trim() !== output.trim()) {
    console.error('✗ orbit-manifest.md is out of date. Run `npm run build:manifest`.');
    process.exit(1);
  }
  console.log('✓ orbit-manifest.md is up to date');
} else {
  writeFileSync(OUTPUT, output);
  console.log(`✓ Wrote orbit-manifest.md (${output.match(/^## /gm)?.length ?? 0} sections)`);
}
